# -*- coding: utf-8 -*-
"""DATA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QugO9hsGByw9DThKV1XxOrJY6deg3qaR
"""

import pandas as pd

data = pd.read_csv('AraCovidVac.csv')

data.shape , data.head()

import pandas as pd
import matplotlib.pyplot as plt
labels_distribution = data['stance'].value_counts()
# Plot the distribution
plt.figure(figsize=(6,4))
labels_distribution.plot(kind='bar', color='skyblue')
plt.title('Distribution of Labels')
plt.xlabel('Labels')
plt.ylabel('Count')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
labels_distribution = data['stance'].value_counts()

# Plot the distribution as a pie chart
plt.figure(figsize=(5,5))
plt.pie(labels_distribution, labels=labels_distribution.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribution of Labels')
plt.show()

data['stance'].value_counts()

import pandas as pd
data = pd.read_csv('data_f - Copy.csv')
data.head()

data['labels'].value_counts()

import pandas as pd
import matplotlib.pyplot as plt
labels_distribution = data['labels'].value_counts()

# Plot the distribution
plt.figure(figsize=(6,4))
labels_distribution.plot(kind='bar', color='skyblue')
plt.title('Distribution of Labels')
plt.xlabel('Labels')
plt.ylabel('Count')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
labels_distribution = data['labels'].value_counts()

# Plot the distribution as a pie chart
plt.figure(figsize=(5,5))
plt.pie(labels_distribution, labels=labels_distribution.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribution of Labels')
plt.show()

# Sample text dataset
text_dataset = data['sentence']

occurrences = {}
duplicates = []

# Dictionary to store indices of each text
indices = {}

for index, text in enumerate(text_dataset):
    if text in occurrences:
        duplicates.append(text)
        indices[text].append(index)
    else:
        occurrences[text] = 1
        indices[text] = [index]

# Print the duplicates along with their indices
for text in duplicates:
    print(f"Text: {text}, Indices: {indices[text]}")

# snorkel

from snorkel.preprocess.nlp import SpacyPreprocessor

spacy = SpacyPreprocessor(text_field="text", doc_field="doc", memoize=True)

df = pd.read_csv('data_without_duplicates.csv')
df['labels'].value_counts()